FROM ubuntu:latest

# install system-wide deps for python and node
RUN apt-get -yqq update
RUN apt-get -yqq install iputils-ping
RUN apt-get -yqq install wget
RUN apt-get -yqq install nodejs npm
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN apt-get -yqq install git

WORKDIR /opt
RUN git clone https://github.com/paulanthonybland/mustard-seed
WORKDIR /opt/mustard-seed

RUN npm --version

RUN echo "Calling: npm install"
RUN npm install

EXPOSE 3000

RUN echo "Starting npm"

CMD [ "npm", "start" ]

